variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - sim

build:
  stage: build
  tags:
    - efinity
    - linux
  script:
    - source init_env.sh
    - make
  after_script:
    - cat hw/super6502_fpga/outflow/super6502_fpga.err.log

sim:
  stage: sim
  tags:
    - linux
    - efinity
  script:
    - source init_env.sh
    - make sim

