default:
  tags:
    - docker

build-sw:
  stage: build
  image: a2geek/cc65-pipeline
  script:
    - cd sw/
    - make


build-fpga:
  stage: build
  image: bslathi19/modelsim_18.1:lite
  script:
    - cd hw/fpga/
    - qsys-generate /builds/bslathi19/super6502/hw/fpga/sdram_platform.qsys --synthesis=VERILOG --output-directory=/builds/bslathi19/super6502/hw/fpga/sdram_platform --family="MAX 10" --part=10M50DAF484C7G
    - quartus_map super6502 -c super6502

test_addr_decode:
    stage: test
    image: bslathi19/modelsim_18.1:lite
    script:
      - cd hw/fpga/simulation/modelsim/
      - vsim -do "do cs_testbench.do"

test_bb_spi:
    stage: test
    image: bslathi19/modelsim_18.1:lite
    script:
      - cd hw/fpga/simulation/modelsim/
      - vsim -do "do bb_spi_testbench.do"

test-sw:
  stage: test
  image: a2geek/cc65-pipeline
  script:
    - cd sw/
    - make test

test_mm:
    stage: test
    image: bslathi19/modelsim_18.1:lite
    script:
      - cd hw/fpga/simulation/modelsim/
      - vsim -do "do mm_testbench.do"

test_crc7:
    stage: test
    image: bslathi19/modelsim_18.1:lite
    script:
      - cd hw/fpga/simulation/modelsim/
      - vsim -do "do crc7_testbench.do"
