// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package tcp_top_regfile_pkg;

    localparam TCP_TOP_REGFILE_DATA_WIDTH = 32;
    localparam TCP_TOP_REGFILE_MIN_ADDR_WIDTH = 9;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } tcp_stream__external__in_t;

    typedef struct {
        tcp_stream__external__in_t tcp_streams[8];
    } tcp_top_regfile__in_t;

    typedef struct {
        logic req;
        logic [4:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } tcp_stream__external__out_t;

    typedef struct {
        tcp_stream__external__out_t tcp_streams[8];
    } tcp_top_regfile__out_t;
endpackage
