// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module tcp_stream_regs (
        input wire clk,
        input wire rst,

        input wire s_cpuif_req,
        input wire s_cpuif_req_is_wr,
        input wire [4:0] s_cpuif_addr,
        input wire [31:0] s_cpuif_wr_data,
        input wire [31:0] s_cpuif_wr_biten,
        output wire s_cpuif_req_stall_wr,
        output wire s_cpuif_req_stall_rd,
        output wire s_cpuif_rd_ack,
        output wire s_cpuif_rd_err,
        output wire [31:0] s_cpuif_rd_data,
        output wire s_cpuif_wr_ack,
        output wire s_cpuif_wr_err,

        input tcp_stream_regs_pkg::tcp_stream_regs__in_t hwif_in,
        output tcp_stream_regs_pkg::tcp_stream_regs__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [4:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    assign cpuif_req = s_cpuif_req;
    assign cpuif_req_is_wr = s_cpuif_req_is_wr;
    assign cpuif_addr = s_cpuif_addr;
    assign cpuif_wr_data = s_cpuif_wr_data;
    assign cpuif_wr_biten = s_cpuif_wr_biten;
    assign s_cpuif_req_stall_wr = cpuif_req_stall_wr;
    assign s_cpuif_req_stall_rd = cpuif_req_stall_rd;
    assign s_cpuif_rd_ack = cpuif_rd_ack;
    assign s_cpuif_rd_err = cpuif_rd_err;
    assign s_cpuif_rd_data = cpuif_rd_data;
    assign s_cpuif_wr_ack = cpuif_wr_ack;
    assign s_cpuif_wr_err = cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            logic source_port;
            logic source_ip;
            logic dest_port;
            logic dest_ip;
            logic control;
        } tcp_streams;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        decoded_reg_strb.tcp_streams.source_port = cpuif_req_masked & (cpuif_addr == 5'h0);
        decoded_reg_strb.tcp_streams.source_ip = cpuif_req_masked & (cpuif_addr == 5'h4);
        decoded_reg_strb.tcp_streams.dest_port = cpuif_req_masked & (cpuif_addr == 5'h8);
        decoded_reg_strb.tcp_streams.dest_ip = cpuif_req_masked & (cpuif_addr == 5'hc);
        decoded_reg_strb.tcp_streams.control = cpuif_req_masked & (cpuif_addr == 5'h10);
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } d;
            } source_port;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } d;
            } source_ip;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } d;
            } dest_port;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } d;
            } dest_ip;
            struct {
                struct {
                    logic next;
                    logic load_next;
                } enable;
                struct {
                    logic next;
                    logic load_next;
                } open;
                struct {
                    logic next;
                    logic load_next;
                } close;
            } control;
        } tcp_streams;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                struct {
                    logic [31:0] value;
                } d;
            } source_port;
            struct {
                struct {
                    logic [31:0] value;
                } d;
            } source_ip;
            struct {
                struct {
                    logic [31:0] value;
                } d;
            } dest_port;
            struct {
                struct {
                    logic [31:0] value;
                } d;
            } dest_ip;
            struct {
                struct {
                    logic value;
                } enable;
                struct {
                    logic value;
                } open;
                struct {
                    logic value;
                } close;
            } control;
        } tcp_streams;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: tcp_stream_regs.tcp_streams.source_port.d
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.tcp_streams.source_port.d.value;
        load_next_c = '0;
        if(decoded_reg_strb.tcp_streams.source_port && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.tcp_streams.source_port.d.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.tcp_streams.source_port.d.next = next_c;
        field_combo.tcp_streams.source_port.d.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.tcp_streams.source_port.d.value <= 32'h0;
        end else if(field_combo.tcp_streams.source_port.d.load_next) begin
            field_storage.tcp_streams.source_port.d.value <= field_combo.tcp_streams.source_port.d.next;
        end
    end
    assign hwif_out.tcp_streams.source_port.d.value = field_storage.tcp_streams.source_port.d.value;
    // Field: tcp_stream_regs.tcp_streams.source_ip.d
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.tcp_streams.source_ip.d.value;
        load_next_c = '0;
        if(decoded_reg_strb.tcp_streams.source_ip && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.tcp_streams.source_ip.d.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.tcp_streams.source_ip.d.next = next_c;
        field_combo.tcp_streams.source_ip.d.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.tcp_streams.source_ip.d.value <= 32'h0;
        end else if(field_combo.tcp_streams.source_ip.d.load_next) begin
            field_storage.tcp_streams.source_ip.d.value <= field_combo.tcp_streams.source_ip.d.next;
        end
    end
    assign hwif_out.tcp_streams.source_ip.d.value = field_storage.tcp_streams.source_ip.d.value;
    // Field: tcp_stream_regs.tcp_streams.dest_port.d
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.tcp_streams.dest_port.d.value;
        load_next_c = '0;
        if(decoded_reg_strb.tcp_streams.dest_port && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.tcp_streams.dest_port.d.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.tcp_streams.dest_port.d.next = next_c;
        field_combo.tcp_streams.dest_port.d.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.tcp_streams.dest_port.d.value <= 32'h0;
        end else if(field_combo.tcp_streams.dest_port.d.load_next) begin
            field_storage.tcp_streams.dest_port.d.value <= field_combo.tcp_streams.dest_port.d.next;
        end
    end
    assign hwif_out.tcp_streams.dest_port.d.value = field_storage.tcp_streams.dest_port.d.value;
    // Field: tcp_stream_regs.tcp_streams.dest_ip.d
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.tcp_streams.dest_ip.d.value;
        load_next_c = '0;
        if(decoded_reg_strb.tcp_streams.dest_ip && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.tcp_streams.dest_ip.d.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.tcp_streams.dest_ip.d.next = next_c;
        field_combo.tcp_streams.dest_ip.d.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.tcp_streams.dest_ip.d.value <= 32'h0;
        end else if(field_combo.tcp_streams.dest_ip.d.load_next) begin
            field_storage.tcp_streams.dest_ip.d.value <= field_combo.tcp_streams.dest_ip.d.next;
        end
    end
    assign hwif_out.tcp_streams.dest_ip.d.value = field_storage.tcp_streams.dest_ip.d.value;
    // Field: tcp_stream_regs.tcp_streams.control.enable
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.tcp_streams.control.enable.value;
        load_next_c = '0;
        if(decoded_reg_strb.tcp_streams.control && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.tcp_streams.control.enable.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.tcp_streams.control.enable.next = next_c;
        field_combo.tcp_streams.control.enable.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.tcp_streams.control.enable.value <= 1'h0;
        end else if(field_combo.tcp_streams.control.enable.load_next) begin
            field_storage.tcp_streams.control.enable.value <= field_combo.tcp_streams.control.enable.next;
        end
    end
    assign hwif_out.tcp_streams.control.enable.value = field_storage.tcp_streams.control.enable.value;
    // Field: tcp_stream_regs.tcp_streams.control.open
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.tcp_streams.control.open.value;
        load_next_c = '0;
        if(decoded_reg_strb.tcp_streams.control && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.tcp_streams.control.open.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end else if(hwif_in.tcp_streams.control.open.hwclr) begin // HW Clear
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.tcp_streams.control.open.next = next_c;
        field_combo.tcp_streams.control.open.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.tcp_streams.control.open.value <= 1'h0;
        end else if(field_combo.tcp_streams.control.open.load_next) begin
            field_storage.tcp_streams.control.open.value <= field_combo.tcp_streams.control.open.next;
        end
    end
    assign hwif_out.tcp_streams.control.open.value = field_storage.tcp_streams.control.open.value;
    // Field: tcp_stream_regs.tcp_streams.control.close
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.tcp_streams.control.close.value;
        load_next_c = '0;
        if(decoded_reg_strb.tcp_streams.control && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.tcp_streams.control.close.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end else if(hwif_in.tcp_streams.control.close.hwclr) begin // HW Clear
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.tcp_streams.control.close.next = next_c;
        field_combo.tcp_streams.control.close.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.tcp_streams.control.close.value <= 1'h0;
        end else if(field_combo.tcp_streams.control.close.load_next) begin
            field_storage.tcp_streams.control.close.value <= field_combo.tcp_streams.control.close.next;
        end
    end
    assign hwif_out.tcp_streams.control.close.value = field_storage.tcp_streams.control.close.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[5];
    assign readback_array[0][31:0] = (decoded_reg_strb.tcp_streams.source_port && !decoded_req_is_wr) ? field_storage.tcp_streams.source_port.d.value : '0;
    assign readback_array[1][31:0] = (decoded_reg_strb.tcp_streams.source_ip && !decoded_req_is_wr) ? field_storage.tcp_streams.source_ip.d.value : '0;
    assign readback_array[2][31:0] = (decoded_reg_strb.tcp_streams.dest_port && !decoded_req_is_wr) ? field_storage.tcp_streams.dest_port.d.value : '0;
    assign readback_array[3][31:0] = (decoded_reg_strb.tcp_streams.dest_ip && !decoded_req_is_wr) ? field_storage.tcp_streams.dest_ip.d.value : '0;
    assign readback_array[4][0:0] = (decoded_reg_strb.tcp_streams.control && !decoded_req_is_wr) ? field_storage.tcp_streams.control.enable.value : '0;
    assign readback_array[4][1:1] = (decoded_reg_strb.tcp_streams.control && !decoded_req_is_wr) ? field_storage.tcp_streams.control.open.value : '0;
    assign readback_array[4][2:2] = (decoded_reg_strb.tcp_streams.control && !decoded_req_is_wr) ? field_storage.tcp_streams.control.close.value : '0;
    assign readback_array[4][5:3] = (decoded_reg_strb.tcp_streams.control && !decoded_req_is_wr) ? hwif_in.tcp_streams.control.state.next : '0;
    assign readback_array[4][31:6] = '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<5; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
