// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package tcp_stream_regs_pkg;

    localparam TCP_STREAM_REGS_DATA_WIDTH = 32;
    localparam TCP_STREAM_REGS_MIN_ADDR_WIDTH = 5;

    typedef struct {
        logic hwclr;
    } tcp_stream__control__open__in_t;

    typedef struct {
        logic hwclr;
    } tcp_stream__control__close__in_t;

    typedef struct {
        logic [2:0] next;
    } tcp_stream__control__state__in_t;

    typedef struct {
        tcp_stream__control__open__in_t open;
        tcp_stream__control__close__in_t close;
        tcp_stream__control__state__in_t state;
    } tcp_stream__control__in_t;

    typedef struct {
        tcp_stream__control__in_t control;
    } tcp_stream__in_t;

    typedef struct {
        tcp_stream__in_t tcp_streams;
    } tcp_stream_regs__in_t;

    typedef struct {
        logic [31:0] value;
    } tcp_stream__source_port__d__out_t;

    typedef struct {
        tcp_stream__source_port__d__out_t d;
    } tcp_stream__source_port__out_t;

    typedef struct {
        logic [31:0] value;
    } tcp_stream__source_ip__d__out_t;

    typedef struct {
        tcp_stream__source_ip__d__out_t d;
    } tcp_stream__source_ip__out_t;

    typedef struct {
        logic [31:0] value;
    } tcp_stream__dest_port__d__out_t;

    typedef struct {
        tcp_stream__dest_port__d__out_t d;
    } tcp_stream__dest_port__out_t;

    typedef struct {
        logic [31:0] value;
    } tcp_stream__dest_ip__d__out_t;

    typedef struct {
        tcp_stream__dest_ip__d__out_t d;
    } tcp_stream__dest_ip__out_t;

    typedef struct {
        logic value;
    } tcp_stream__control__enable__out_t;

    typedef struct {
        logic value;
    } tcp_stream__control__open__out_t;

    typedef struct {
        logic value;
    } tcp_stream__control__close__out_t;

    typedef struct {
        tcp_stream__control__enable__out_t enable;
        tcp_stream__control__open__out_t open;
        tcp_stream__control__close__out_t close;
    } tcp_stream__control__out_t;

    typedef struct {
        tcp_stream__source_port__out_t source_port;
        tcp_stream__source_ip__out_t source_ip;
        tcp_stream__dest_port__out_t dest_port;
        tcp_stream__dest_ip__out_t dest_ip;
        tcp_stream__control__out_t control;
    } tcp_stream__out_t;

    typedef struct {
        tcp_stream__out_t tcp_streams;
    } tcp_stream_regs__out_t;
endpackage
